const IconsCofig = [
  'sort',
  'address-book',
  'angle-double-down',
  'angle-double-left',
  'angle-down',
  'angle-up',
  'backward',
  'baby-carriage',
  'battery-half',
  'biking',
  'swimmer',
  'arrow-circle-right',
  'arrow-circle-up',
  'calendar-check',
  'camera',
  'chart-bar',
  'chart-pie',
  'cloud-moon-rain',
  'cloud-sun',
  'code-branch',
  'coffee',
  'cogs',
  'comment-alt',
  'comments',
];

export default IconsCofig;
